sistema/gestantes/urls.py
from  django.urls import path
from .views import home,formulario, datos,semanal, registros,asociados, mensual, generar_excel_semanal, generar_excel_mensual, eliminar_mensual
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('',home,name='home'),
  path('formulario',formulario,name='formulario'),
  path('semanal',datos,name='datos'),
  path('semanal/generar',generar_excel_semanal, name='generar_excel_semanal'),
  path('registros',registros, name='registros'),
  path('mostrar/<str:tipo_cedula>/<str:numero_cedula>/',asociados, name='mostrar'),
  path('mensual',mensual, name='mensual'),
  path('mensual/mensual', generar_excel_mensual, name='generar_excel_mensual'),
  path('eliminar_mensual/<int:datosgestante_id>/',eliminar_mensual, name='elimina_mensual'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) """

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('gestantes.urls'))
]

sistema/gestantes/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError



# Create your models here.


def user_directory_path(instance, filename):
    ruta = 'SOPORTES_GESTANTES'
    return '{0}/{1}/{2}/{3}/{4}/{5}'.format(ruta, instance.regional,
                                    instance.prestador,
                                    instance.tipdoc,
                                    instance.identificacion,
                                    instance.tipoar,
                                    filename)



class DatosGestante(models.Model):

    TIPDOC = (
        ('CC', 'CEDULA DE CIUDA'),
        ('CE', 'CEDULA DE EXTR.'),
        ('MS', 'MENOR SIN IDENT'),
        ('NU', 'N.UNICO IDENT'),
        ('PA', 'PASAPORTE'),
        ('RC', 'REGISTRO CIVIL'),
        ('TI', 'TARJETA IDENT.'),
        ('PE', 'PERMISO PERMANE'),
        ('CN', 'NACIDO VIVO'),
        ('SC', 'SALVO CONDUTO'),
        ('AS', 'ADULTO SIN IDEN'),
        ('PT', 'PER PROTEC TEMP'),
    )

    tipo_archivo = models.IntegerField('Tipo archivo', default=2)
    tipdoc = models.CharField('Tipo de documento', max_length=2, null=True, blank=True)
    nro_doc = models.CharField("Documento de identificación", max_length=25, db_index=True)
    fecha_parto = models.DateField('Fecha de parto')
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    objects = models.Manager()

    def __str__(self):
        return str(self.nro_doc)

    class Meta:
        ordering = ["nro_doc"]


class ActividadGestante(models.Model):

    CLASIF = (
        ('4', 'Alto riesgo'),
        ('5', 'Bajo riesgo'),
        ('21', 'Riesgo no evaluado'),
    )

    SUMIN = (
        ('0', 'No aplica'),
        ('1', 'Si se suministra'),
        ('21', 'Riesgo no evaluado'),
    )

    SUMAC = (
        ('0', 'No aplica'),
        ('1', 'Dispositivo intrauterino'),
        ('2', 'Dispositivo intrauterino y preservativo'),
        ('3', 'implante sudérmico'),
        ('4', 'implante sudérmico y preservativo '),
        ('5', 'Oral'),
        ('6', 'Oral y preservativo'),
        ('7', 'Inyectable mensual'),
        ('8', 'Inyectable mensual y preservativo'),
        ('9', 'Inyectable trimestral'),
        ('10', 'Inyectable trimestral y preservativo'),
        ('13', 'Esterilización'),
        ('14', 'Esterilización y preservativo'),
        ('15', 'Preservativo'),
    )

    tipo_archivo = models.IntegerField('Tipo archivo', default=2)
    fecha_parto = models.DateField('Fecha de parto')
    cod_cups = models.CharField('codigo cups', max_length=25, null=True, blank=True, db_index=True)
    finalidad = models.CharField('Finalidad tecnologia salud', max_length=2, null=True, blank=True)
    clas_ries_ges = models.CharField('Clasificación riesgo gestacional', max_length=2, choices=CLASIF)
    clas_ries_precl = models.CharField('Clasificación riesgo preclampsia', max_length=2, choices=CLASIF)
    suministro_asa = models.CharField('Suministro asa', max_length=2, choices=SUMIN)
    suministro_acido = models.CharField('Suministro acido folico', max_length=2, choices=SUMIN)
    suministro_sulfato = models.CharField('Suministro sulfato ferroso', max_length=2, choices=SUMIN)
    suministro_calcio = models.CharField('Suministro calcio ', max_length=2, choices=SUMIN)
    fecha_suministro = models.DateField('Fecha suministro')
    suministro_antic = models.CharField('Suministro anticonceptivo ', max_length=2, choices=SUMAC)
    fecha_salida = models.DateField('Fecha salida atención parto cesarea')
    datosgestante = models.ForeignKey(DatosGestante, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    objects = models.Manager()

    def __str__(self):
        return str(self.cod_cups)

    class Meta:
        ordering = ["cod_cups"]


class SeguimientoGestante(models.Model):

    TIPOCA = (
        ('1', 'Mayor de 95 años'),
        ('2', 'Alteraciones nutricionales'),
        ('3', 'Consulta a servicios de urgencias'),
        ('4', 'Hospitalización'),
        ('5', 'Laboratorios alterados'),
        ('6', 'Antecendes de preeclampsia'),
        ('7', 'Riesgo de preeclampsia'),
        ('8', 'Menos de cuatro controles prenatales mediando la semana gestacional 30'),
        ('9', 'Morbilidad materna externa'),
        ('10', 'Riesgo de tromboembolismo'),
        ('10', 'Diagnóstico de enfermedad del colágeno'),
        ('10', 'Diagnóstico de algún tipo de cáncer'),

    )

    SUMIN = (
        ('0', 'No aplica'),
        ('1', 'Si se suministra'),
        ('21', 'Riesgo no evaluado'),
    )

    RPTA = (
        ('1', 'SI'),
        ('2', 'NO'),

    )

    TSEGUI = (
        ('1', 'Contacto telefónico'),
        ('2', 'Visita domiciliaria'),
        ('3', 'Visita de auditor concurrente en hospitalización'),
        ('4', 'Otro'),

    )

    tipo_archivo = models.IntegerField('Tipo archivo', default=2)
    tipo_caso = models.CharField('Tipo caso', max_length=2, choices=TIPOCA)
    fecha_seguimiento = models.DateField('Fecha de seguimiento')
    tipo_seguimiento = models.CharField('Tipo de seguimiento', max_length=2, choices=TSEGUI)
    asig_cita_pm = models.CharField('Asignación cita profesional medicina', max_length=2, choices=RPTA)
    asig_cita_me = models.CharField('Asignación cita medicina especializada', max_length=2, choices=RPTA)
    referencia_inst = models.CharField('Referencia mayor complejidad', max_length=2, choices=RPTA)
    can_entrega_med = models.CharField('Canalización entrega de medicamentos', max_length=2, choices=RPTA)
    entrega_med = models.CharField('Entrega de medicamentos', max_length=2, choices=RPTA)
    info_ciudado_sal = models.CharField('Información cuidado salud', max_length=2, choices=RPTA)
    datosgestante = models.ForeignKey(DatosGestante, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    objects = models.Manager()

    def __str__(self):
        return str(self.tipo_caso)


class SoporteGestante(models.Model):
    TIPOCA = (
    ('IC', 'Inicio de control'),
    ('VH', 'VIH'),
    ('SF', 'Sifilis'),
    ('HC', 'Historia clinica'),
    )
    tipo_arch = models.CharField('Tipo archivo', max_length=2, choices=TIPOCA)
    soporte = models.FileField('Soporte',
                               validators=[FileExtensionValidator(['pdf'])])
    datosgestante = models.ForeignKey(DatosGestante, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    objects = models.Manager()

    def __str__(self):
        return str(self.soporte)

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.soporte.path):
            os.remove(self.soporte.path)
        super(SoporteGestante, self).delete(*args, **kwargs)



def validate_excel_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.xlsx', '.xls']
    if not ext.lower() in valid_extensions:
        raise ValidationError("Por favor, suba un archivo Excel válido (xlsx o xls).")

class CargueMensual(models.Model):
    soporte_excel = models.FileField('Soporte Excel', validators=[validate_excel_file_extension])
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    def __str__(self):
        return self.soporte_excel



class InformacionGestante(models.Model):
    OBSERVACIONES_PARA_SEGUIMIENTO = models.TextField('OBSERVACIONES PARA SEGUIMIENTO')
    RESPONSABLE_DE_LA_ZONA = models.CharField('RESPONSABLE DE LA ZONA',max_length=255)
    PUNTO_O_CENTRO_DE_ATENCION = models.CharField('PUNTO O CENTRO DE ATENCION',max_length=255)
    ATENCION_PRECONCEPCIONAL = models.CharField('ATENCIÓN PRECONCEPCIONAL',max_length=255)
    APELLIDO = models.CharField('APELLIDO',max_length=255)
    APELLIDO2 = models.CharField('APELLIDO 2',max_length=255)
    NOMBRE1 = models.CharField('NOMBRE 1',max_length=255)
    cargue_mensual = models.ForeignKey(CargueMensual, on_delete=models.CASCADE, related_name='informacion_gestante')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    objects = models.Manager()


class InformacionMensual(models.Model):
    var1 = models.TextField('Observaciones Seguimiento', null=True, blank=True)
    var2 = models.CharField('Responsable zona', max_length=50, null=True, blank=True)
    var3 = models.CharField('Punto Atencion', max_length=60, null=True, blank=True)
    var4 = models.CharField('Atencion_Preconcepcional', max_length=50, null=True, blank=True)
    var5 = models.CharField("Primer nombre", max_length=60, null=True, blank=True)
    var6 = models.CharField("Segundo nombre", max_length=60, null=True, blank=True)
    var7 = models.CharField("Primer apellido", max_length=60, null=True, blank=True)
    var8 = models.CharField("Segundo apellido", max_length=60, null=True, blank=True)
    var9 = models.CharField('Tipo de documento', max_length=2, null=True, blank=True)
    var10 = models.CharField("Documento de identificación", max_length=25, null=True, blank=True, db_index=True)
    var11 = models.CharField("Estado Civil", max_length=20, null=True, blank=True)

sistema/gestantes/forms.py
from django import forms
from .models import DatosGestante,ActividadGestante,SeguimientoGestante,SoporteGestante, CargueMensual

class DatosGestanteForm(forms.ModelForm):
    class Meta:
        model = DatosGestante  
        fields = [
    
            'tipdoc',
            'nro_doc',
            'fecha_parto',
  
        ]
        widgets = {
            'fecha_parto': forms.DateInput(attrs={'type': 'date'}),
        }

class ActividadGestanteForm(forms.ModelForm):
    class Meta:
        model = ActividadGestante
        fields = [
    
            'fecha_parto',
            'cod_cups',
            'finalidad',
            'clas_ries_ges',
            'clas_ries_precl',
            'suministro_asa',
            'suministro_acido',
            'suministro_sulfato',
            'suministro_calcio',
            'fecha_suministro',
            'suministro_antic',
            'fecha_salida',
   
          
        ]
        widgets = {
            'fecha_parto': forms.DateInput(attrs={'type': 'date'}),
            'fecha_suministro': forms.DateInput(attrs={'type': 'date'}),
            'fecha_salida': forms.DateInput(attrs={'type': 'date'}),
        }

class SeguimientoGestanteForm(forms.ModelForm):
    class Meta:
        model = SeguimientoGestante
        fields = [

            'tipo_caso',
            'fecha_seguimiento',
            'tipo_seguimiento',
            'asig_cita_pm',
            'asig_cita_me',
            'referencia_inst',
            'can_entrega_med',
            'entrega_med',
            'info_ciudado_sal',
     
          
        ]
        widgets = {
            'fecha_seguimiento': forms.DateInput(attrs={'type': 'date'})
        }

class SoporteGestanteForm(forms.ModelForm):
    class Meta:
        model = SoporteGestante
        fields = ['tipo_arch', 'soporte']

    def clean_soporte(self):
        soporte = self.cleaned_data.get('soporte')

        if soporte:
            file_extension = soporte.name.split('.')[-1].lower()
            if file_extension != 'pdf':
                raise forms.ValidationError('El archivo debe ser en formato PDF.')

        return soporte
    

class CargueMensualForm(forms.ModelForm):
    class Meta:
        model = CargueMensual
        fields = ['soporte_excel']

    def clean_soporte_excel(self):
        soporte_excel = self.cleaned_data.get('soporte_excel')
        if soporte_excel:
            ext = soporte_excel.name.split('.')[-1].lower()
            if ext not in ['xls', 'xlsx']:
                raise forms.ValidationError("Por favor, suba un archivo Excel válido (xlsx o xls).")
        return soporte_excel

sistema/gestantes/templates/plantillas/hola.html
<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>
  <header>
    <!-- place navbar here -->
  </header>
  <main>

  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

sistema/gestantes/templates/plantillas/martes.html
<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>
  <header>
    <!-- place navbar here -->
  </header>
  <main>

  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

sistema/gestantes/templates/plantillas/tablas_formulario.html
<fieldset data-step="1">
  <div class="container ">
      <p class="title_form">Ingrese la siguiente información relacionada con la gestante.</p>
      <div class="row form_row">
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
                
      <!--           <label for="tipo_identificacion" >Tipo de archivo</label>
                <input type="text" id="id_tipo_archivo" name="tipo_archivo" value="{{ form_datos_gestante.tipo_archivo.value }}"> -->
                  <label for="segundo_nombre">Segundo Nombre</label>
                  <input type="text" id="segundo_nombre" name="segundo_nombre" placeholder="Ingrese Segundo Nombre">
                  <label for="fecha_nacimiento">Fecha de Nacimiento</label>
                  <input type="text" id="fecha_nacimiento"
                      name="fecha_nacimiento" placeholder="Ingrese fecha de nacimiento">
                  <label for="codigo_nivel_educativo">Código Nivel Educativo</label>
                  <input type="text" id="codigo_nivel_educativo"
                      name="codigo_nivel_educativo" placeholder="Ingrese Nivel Educativo">
                  <label for="codigo_municipio">Código Municipio</label>
                  <input type="text" id="codigo_municipio"
                      name="codigo_municipio" placeholder="Ingrese Municipio">
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
             <label for="numero_identificacion">Número de Identificación</label>
                  <input type="text" id="numero_identificacion"
                      name="numero_identificacion"  placeholder="Ingrese Número de Identificación">
                  <label for="primer_apellido">Primer Apellido</label>
                  <input type="text" id="primer_apellido"
                      name="primer_apellido"  placeholder="Ingrese Primer Apellido">
                  <label for="codigo_etnica">Étnica</label>
                  <input type="text" id="codigo_etnica" name="codigo_etnica"  placeholder="Ingrese Étnia">
                  <label for="fecha_posible_parto">Fecha Posible Parto</label>
                  <input type="text" id="fecha_posible_parto"
                      name="fecha_posible_parto"  placeholder="Ingrese Fecha Posible de Parto">
                  <label for="zona_territorial">Zona Territorial</label>
                  <input type="text" id="zona_territorial"
                      name="zona_territorial"  placeholder="Ingrese Zona Territorial">
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
           <label for="primer_nombre">Primer Nombre</label>
                  <input type="text" id="primer_nombre" name="primer_nombre" placeholder="Ingrese Primer Nombre">
                  <label for="segundo_apellido">Segundo Apellido</label>
                  <input type="text" id="segundo_apellido"
                      name="segundo_apellido" placeholder="Ingrese Segundo Apellidp">
                  <label for="codigo_ocupacion">Ocupación</label>
                  <input type="text" id="codigo_ocupacion"
                      name="codigo_ocupacion" placeholder="Ingrese Ocupación">
                  <label for="codigo_nacionalidad">Nacionalidad</label>
                  <input type="text" id="codigo_nacionalidad"
                      name="codigo_nacionalidad" placeholder="Ingrese Nacionalidad"> 
              </div>
          </div>
      </div>
  </div>
  <div class="f1-buttons">
      <button type="button" class="btn btn-close"><i class="fas fa-walking"></i>Cerrar</button>
      <button type="button" class="btn btn-next">Siguiente<i class="fas fa-forward"></i></button>
  </div>
</fieldset>

<fieldset data-step="2">
  <div class="container">
      <p class="title_form">Ingrese la siguiente información relacionada con la gestante.</p>
      <div class="row form_row">
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
                  <label for="id_fecha_tecnologia_salud">Fecha Tecnología en Salud</label>
                  <input type="text" id="id_fecha_tecnologia_salud"
                      name="fecha_tecnologia_salud"  placeholder="Ingrese Fecha Tecnología en Salud"/>
                  <label for="id_codigo_cups">Código CUPS</label>
                  <input type="text" id="id_codigo_cups" name="codigo_cups" placeholder="Ingrese Código Cups"/>
                  <label for="id_finalidad_tecnologia">Finalidad Tecnología</label>
                  <input type="text" id="id_finalidad_tecnologia"
                      name="finalidad_tecnologia" placeholder="Ingrese Finalidad de Tecnología"/>
                  <label for="id_clasificacion_riesgo_gestacional">Clasificación
                      Riesgo Gestacional</label>
                  <input type="text" id="id_clasificacion_riesgo_gestacional"
                      name="clasificacion_riesgo_gestacional" placeholder="Seleccione Clasificación Riesgo Gestacional"/>
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
                  <label for="id_suministro_post">Fecha Suministro Post Evento</label>
                  <input type="text" id="id_suministro_post"
                      name="suministro_post" placeholder="Ingrese Fecha Suministro Post "/>
                  <label for="id_fecha_parto">Fecha de Parto o Cesárea</label>
                  <input type="text" id="id_fecha_parto"
                      name="fecha_parto" placeholder="Ingrese Fecha Parto/Cesárea"/>
                  <label for="id_riesgo_preclampsia">Riesgo Preeclampsia</label>
                  <input type="text" id="id_riesgo_preeclampsia"
                      name="riesgo_preeclampsia" placeholder="Seleccione una Opción"/>
                  <label for="id_suministro_calsio">Suministro Calcio</label>
                  <input type="text" id="id_suministro_calsio"
                      name="suministro_calsio" placeholder="Seleccione una Opción"/>
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
                  <label for="id_suministro_acetil">Suministro Ácido Acetilsalicílico</label>
                  <input type="text" id="id_suministro_acetil"
                      name="suministro_acetil" placeholder="Seleccione una Opción" />
                  <label for="id_suministro_folico">Suministro Ácido Fólico</label>
                  <input type="text" id="id_suministro_folico"
                      name="suministro_folico" placeholder="Seleccione una Opción" />
                  <label for="id_suministro_sulfato">Suministro Sulfato Ferroso</label>
                  <input type="text" id="id_suministro_sulfato"
                      name="suministro_sulfato" placeholder="Seleccione una Opción"/>
                  <label for="id_suministro_anticonceptivo">Suministro Anticonceptivoo</label>
                  <input type="text" id="id_suministro_anticonceptivo"
                      name="suministro_anticonceptivo" placeholder="Seleccione una Opción"/>
              </div>
          </div>
      </div>
  </div>
  <div class="f1-buttons">
      <button type="button" class="btn btn-previous">Atras</button>
      <button type="button" class="btn btn-next">Siguiente<i class="fas fa-forward"></i></button>
  </div>
</fieldset>

<!-- Seguimiento -->
<fieldset data-step="3">
  <div class="container">
      <p class="title_form">Ingrese la siguiente información relacionada con la gestante.</p>
      <div class="row form_row">
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
              <label for="id_tipo_caso">Tipo de Caso</label>
              <input type="text" id="id_tipo_caso" name="tipo_caso" placeholder="Seleccione una opción"/>
              <label for="id_seguimiento_cita_profesional_medicina">Cita Profesional Medicina</label>
              <input type="text" id="id_seguimiento_cita_profesional_medicina"
                  name="seguimiento_cita_profesional_medicina" placeholder="Seleccione una opción"/>
              <label for="id_seguimiento_cita_procedimientos">Cita Procedimientos</label>
              <input type="text" id="id_seguimiento_cita_procedimientos"
                  name="seguimiento_cita_procedimientos" placeholder="Seleccione una opción" />
              <label for="id_seguimiento_informacion_cuidado_salud">Información Cuidado Salud</label>
              <input type="text" id="id_seguimiento_informacion_cuidado_salud"
                  name="seguimiento_informacion_cuidado_salud" placeholder="Seleccione una opción"/>
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
              <label for="id_fecha_seguimiento">Fecha Seguimiento</label>
              <input type="text" id="id_fecha_seguimiento"
                  name="fecha_seguimiento" placeholder="Seleccione fecha de seguimiento"/>
              <label for="id_seguimiento_cita_medicina_especializada">Cita Medicina Especializada</label>
              <input type="text"
                  id="id_seguimiento_cita_medicina_especializada"
                  name="seguimiento_cita_medicina_especializada" placeholder="Seleccione una opción"/>
              <label for="id_seguimiento_entrega_resultados_laboratorio">  Entrega Resultados Laboratorio</label>
              <input type="text"
                  id="id_seguimiento_entrega_resultados_laboratorio"
                  name="seguimiento_entrega_resultados_laboratorio" placeholder="Seleccione una opción"/>
              </div>
          </div>
          <div class="col-xs-12 col-sm-4">
              <div class="form-group">
              <label for="id_tipo_seguimiento">Tipo Seguimiento</label>
              <input type="text" id="id_tipo_seguimiento"
                  name="tipo_seguimiento" placeholder="Seleccione una opción"/>
              <label for="id_seguimiento_referencia_mayor_complejidad">Referencia Mayor Complejidad</label>
              <input type="text"
                  id="id_seguimiento_referencia_mayor_complejidad"
                  name="seguimiento_referencia_mayor_complejidad" placeholder="Seleccione una opción" />
              <label for="id_seguimiento_entrega_medicamentos">Entrega Medicamentos</label>
              <input type="text" id="id_seguimiento_entrega_medicamentos"
                  name="seguimiento_entrega_medicamentos" placeholder="Seleccione una opción" />
              </div>
          </div>
      </div>
  </div>
  <div class="f1-buttons">
      <button type="button" class="btn btn-previous">Atras</button>
      <button type="button" class="btn btn-next">Siguiente<i class="fas fa-forward"></i></button>
  </div>
</fieldset>

<fieldset data-step="4">
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <label for="tipo_actividad">Tipo de Actividad</label>
              <input type="text" id="tipo_actividad" name="tipo_actividad">
          </div>
          <div class="col-md-4">
              <label for="archivo">Archivo</label>
              <input type="file" id="archivo" name="archivo">
          </div>
          <div class="col-md-4">
              <!-- Columna vacía -->
          </div>
      </div>
  </div>
  <div class="f1-buttons">
      <button type="button" class="btn btn-previous">Atras</button>
      <input type="submit" value="Guardar" />
  </div>
</fieldset>